# Arrays

### Reverse array

In [17]:
s=['h','e','l', 'l','0']
s.reverse()

In [18]:
#1. Using Recursion
class Solution: #Time O(N), space: O(N)
    def reverseString(self, s):
        def helper(left,right):
            if left < right:
                s[left], s[right]=s[right], s[left]
                helper(left+1, right-1)
        helper(0, len(s)-1)
        return s

Solution().reverseString(s)


['h', 'e', 'l', 'l', '0']

In [19]:
#Two pointer 
class Solution: #Time O(N), space: O(1)
    def reverseString(self, s):
        left,right=0, len(s)-1
        while left < right:
            s[left], s[right]=s[right], s[left]
            left, right=left+1, right-1
        return s
    
Solution().reverseString(s)


['0', 'l', 'l', 'e', 'h']

# List operations

min(List) , max(List)  
List[1][2]  
sorted(List)  
List.sort()   
erged_list = list1 + list2  or list1.extend(list2) 

In [ ]:
#min max, 

my_list=[1,5,2,8]

min(my_list), max(my_list)

(1, 8)

In [24]:
#slicing
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list[1][2]

6

In [30]:
#sort
sorted(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
my_list.sort()

In [37]:
# List comprehension
[x for x in range(3)]

[0, 1, 2]

In [35]:

[x**2 for x in range (1,4) if x%2==0]

[4]

In [36]:
[(x,y) for x in range(1,3) for y in range(4,6)]

[(1, 4), (1, 5), (2, 4), (2, 5)]

In [38]:
#Lambda functions
square=lambda x:x**2
square(3)

9

In [41]:
#map
my_list=[1,2,3,4,5]
list(map(lambda x:x*2, my_list))

[2, 4, 6, 8, 10]

In [42]:
#reduce

from functools import reduce
my_list=[1,2,3,4,5]
reduce(lambda x,y: x+y, my_list)

15

In [43]:
#filter

my_list=[1,2,3,4,5]
list(filter(lambda x:x%2==0, my_list))

[2, 4]

In [46]:
#sorted
my_list=[5,2,4,1,3]
sorted(my_list, key=lambda x:x%2==0)

[5, 1, 3, 2, 4]

# Numpy operation

np.min(array), mnp.max(array)   
array.sort()   
np.sort(array)   
np.partition(arry,2)  
np.concatenate((array1, array2)), np.vstack((array1, array2)) , np.hstack((array1, array2))

In [29]:
import numpy as np

#slicing
my_arry=np.array(my_list)
print(my_arry)
my_arry[1,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

In [7]:
#min, max
my_arry=np.array([my_list])
np.min(my_arry), np.max(my_arry)

(1, 8)

In [32]:
#Sort 
my_array = np.array([4, 2, 7, 1, 5])
my_array.sort()

In [33]:
np.sort(my_array)

array([1, 2, 4, 5, 7])

## Dictionary/Hash table vs. List/ArrayList: Very important!!

### Hashtable
key-value, not sorted.
Hash function to map key to index. O(1) time complexity, Fast access to elements based on keys. 


### ArrayList/Dynamic resizable list
ordered collection

In [ ]:
#######################
# When to use Hashtable
#######################
#Key-value mapping
user_info = {"user1": {"name": "Alice", "age": 25}, "user2": {"name": "Bob", "age": 30}}

#Fast lookup
dictionary = {"apple": "a fruit", "banana": "a fruit", "carrot": "a vegetable"}
if "banana" in dictionary:
    print(dictionary["banana"])  # Output: a fruit

##################
# When to use List
##################
#Ordered collection
task_list = ["Task 1", "Task 2", "Task 3"]

#Indexed access
fruits = ["apple", "banana", "orange"]
print(fruits[1])  # Output: banana

#Dynamic resizing
numbers = []
numbers.append(1)
numbers.append(2)
numbers.append(3)

In [48]:
#Dictionary

#Insertion
my_dict = {}  # An empty dictionary
my_dict["key1"] = "value1"  # Insert using assignment operator
my_dict.update({"key2": "value2"})  # Insert using update method
print(my_dict)  # Output: {'key1': 'value1', 'key2': 'value2'}

#Retrieval
my_dict = {"key1": "value1", "key2": "value2"}
value1 = my_dict["key1"]  # Retrieve using square bracket notation
value2 = my_dict.get("key2")  # Retrieve using get() method
print(value1)  # Output: 'value1'
print(value2)  # Output: 'value2'


#Deletion
my_dict = {"key1": "value1", "key2": "value2"}
del my_dict["key1"]  # Delete using del keyword
value = my_dict.pop("key2")  # Delete using pop() method
print(my_dict)  # Output: {}
print(value)  # Output: 'value2'

{'key1': 'value1', 'key2': 'value2'}
value1
value2
{}
value2


# Practice

#
Slicing, Reduce, Filter

### Reverse to make equal
Given two arrays A and B of length N, determine if there is a way to make A equal to B by reversing any subarrays from array B any number of times.  
Signature  
bool areTheyEqual(int[] arr_a, int[] arr_b)  
Input  
All integers in array are in the range [0, 1,000,000,000].  
Output  
Return true if B can be made equal to A, return false otherwise.  
Example  
A = [1, 2, 3, 4]   
B = [1, 4, 3, 2]  
output = true  
After reversing the subarray of B from indices 1 to 3, array B will equal array A.  


In [ ]:

import math

def are_they_equal(array_a, array_b):
  # Write your code here
  for i in range(len(arry_b)):
    if arry_b == reverseArray(arry_b[i::]):
      return True

def reverseArray(arry):
  left, right=0, len(arry)-1
  while left < right:
    arry[left], arry[right]=arry[right], arry[left]
    left, right=left +1, right-1
  


### 2. Passing Yearbooks
There are n students, numbered from 1 to n, each with their own yearbook. They would like to pass their yearbooks around and get them signed by other students.
You're given a list of n integers arr[1..n], which is guaranteed to be a permutation of 1..n (in other words, it includes the integers from 1 to n exactly once each, in some order). The meaning of this list is described below.
Initially, each student is holding their own yearbook. The students will then repeat the following two steps each minute: Each student i will first sign the yearbook that they're currently holding (which may either belong to themselves or to another student), and then they'll pass it to student arr[i-1]. It's possible that arr[i-1] = i for any given i, in which case student i will pass their yearbook back to themselves. Once a student has received their own yearbook back, they will hold on to it and no longer participate in the passing process.
It's guaranteed that, for any possible valid input, each student will eventually receive their own yearbook back and will never end up holding more than one yearbook at a time.
You must compute a list of n integers output, whose element at i-1 is equal to the number of signatures that will be present in student i's yearbook once they receive it back.
Signature
int[] findSignatureCounts(int[] arr)
Input
n is in the range [1, 100,000].
Each value arr[i] is in the range [1, n], and all values in arr[i] are distinct.
Output
Return a list of n integers output, as described above.
Example 1
n = 2
arr = [2, 1]
output = [2, 2]
Pass 1:
Student 1 signs their own yearbook. Then they pass the book to the student at arr[0], which is Student 2.
Student 2 signs their own yearbook. Then they pass the book to the student at arr[1], which is Student 1.
Pass 2:
Student 1 signs Student 2's yearbook. Then they pass it to the student at arr[0], which is Student 2.
Student 2 signs Student 1's yearbook. Then they pass it to the student at arr[1], which is Student 1.
Pass 3:
Both students now hold their own yearbook, so the process is complete.
Each student received 2 signatures.
Example 2
n = 2
arr = [1, 2]
output = [1, 1]
Pass 1:
Student 1 signs their own yearbook. Then they pass the book to the student at arr[0], which is themself, Student 1.
Student 2 signs their own yearbook. Then they pass the book to the student at arr[1], which is themself, Student 2.
Pass 2:
Both students now hold their own yearbook, so the process is complete.
Each student received 1 signature.

In [ ]:
import math
# Add any extra import statements you may need here


# Add any helper functions you may need here


def findSignatureCounts(arr):
  # Write your code here
  
  









# These are the tests we use to determine if the solution is correct.
# You can add your own at the bottom.

def printInteger(n):
  print('[', n, ']', sep='', end='')

def printIntegerList(array):
  size = len(array)
  print('[', end='')
  for i in range(size):
    if i != 0:
      print(', ', end='')
    print(array[i], end='')
  print(']', end='')

test_case_number = 1

def check(expected, output):
  global test_case_number
  expected_size = len(expected)
  output_size = len(output)
  result = True
  if expected_size != output_size:
    result = False
  for i in range(min(expected_size, output_size)):
    result &= (output[i] == expected[i])
  rightTick = '\u2713'
  wrongTick = '\u2717'
  if result:
    print(rightTick, 'Test #', test_case_number, sep='')
  else:
    print(wrongTick, 'Test #', test_case_number, ': Expected ', sep='', end='')
    printIntegerList(expected)
    print(' Your output: ', end='')
    printIntegerList(output)
    print()
  test_case_number += 1

if __name__ == "__main__":
  arr_1 = [2, 1]
  expected_1 = [2, 2]
  output_1 = findSignatureCounts(arr_1)
  check(expected_1, output_1)

  arr_2 = [1, 2]
  expected_2 = [1, 1]
  output_2 = findSignatureCounts(arr_2)
  check(expected_2, output_2)


  # Add your own test cases here
  

## 3. Contiguous Subarrays
You are given an array arr of N integers. For each index i, you are required to determine the number of contiguous subarrays that fulfill the following conditions:
The value at index i must be the maximum element in the contiguous subarrays, and
These contiguous subarrays must either start from or end on index i.
Signature
int[] countSubarrays(int[] arr)
Input
Array arr is a non-empty list of unique integers that range between 1 to 1,000,000,000
Size N is between 1 and 1,000,000
Output
An array where each index i contains an integer denoting the maximum number of contiguous subarrays of arr[i]
Example:
arr = [3, 4, 1, 6, 2]
output = [1, 3, 1, 5, 1]
Explanation:
For index 0 - [3] is the only contiguous subarray that starts (or ends) at index 0 with the maximum value in the subarray being 3.
For index 1 - [4], [3, 4], [4, 1]
For index 2 - [1]
For index 3 - [6], [6, 2], [1, 6], [4, 1, 6], [3, 4, 1, 6]
For index 4 - [2]
So, the answer for the above input is [1, 3, 1, 5, 1]

In [ ]:
import math
# Add any extra import statements you may need here


# Add any helper functions you may need here


def count_subarrays(arr):
  # Write your code here
  
  









# These are the tests we use to determine if the solution is correct.
# You can add your own at the bottom.

def printInteger(n):
  print('[', n, ']', sep='', end='')

def printIntegerList(array):
  size = len(array)
  print('[', end='')
  for i in range(size):
    if i != 0:
      print(', ', end='')
    print(array[i], end='')
  print(']', end='')

test_case_number = 1

def check(expected, output):
  global test_case_number
  expected_size = len(expected)
  output_size = len(output)
  result = True
  if expected_size != output_size:
    result = False
  for i in range(min(expected_size, output_size)):
    result &= (output[i] == expected[i])
  rightTick = '\u2713'
  wrongTick = '\u2717'
  if result:
    print(rightTick, 'Test #', test_case_number, sep='')
  else:
    print(wrongTick, 'Test #', test_case_number, ': Expected ', sep='', end='')
    printIntegerList(expected)
    print(' Your output: ', end='')
    printIntegerList(output)
    print()
  test_case_number += 1

if __name__ == "__main__":
  test_1 = [3, 4, 1, 6, 2]
  expected_1 = [1, 3, 1, 5, 1]
  output_1 = count_subarrays(test_1)
  check(expected_1, output_1)
  
  test_2 = [2, 4, 7, 1, 5, 3]
  expected_2 = [1, 2, 6, 1, 3, 1]
  output_2 = count_subarrays(test_2)
  check(expected_2, output_2)

  # Add your own test cases here
  