# Arrays

### Reverse array

In [17]:
s=['h','e','l', 'l','0']
s.reverse()

In [18]:
#1. Using Recursion
class Solution: #Time O(N), space: O(N)
    def reverseString(self, s):
        def helper(left,right):
            if left < right:
                s[left], s[right]=s[right], s[left]
                helper(left+1, right-1)
        helper(0, len(s)-1)
        return s

Solution().reverseString(s)


['h', 'e', 'l', 'l', '0']

In [19]:
#Two pointer 
class Solution: #Time O(N), space: O(1)
    def reverseString(self, s):
        left,right=0, len(s)-1
        while left < right:
            s[left], s[right]=s[right], s[left]
            left, right=left+1, right-1
        return s
    
Solution().reverseString(s)


['0', 'l', 'l', 'e', 'h']

# List operations

min(List) , max(List)  
List[1][2]  
sorted(List)  
List.sort()   
erged_list = list1 + list2  or list1.extend(list2) 

In [ ]:
#min max, 

my_list=[1,5,2,8]

min(my_list), max(my_list)

(1, 8)

In [24]:
#slicing
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list[1][2]

6

In [30]:
#sort
sorted(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
my_list.sort()

In [37]:
# List comprehension
[x for x in range(3)]

[0, 1, 2]

In [35]:

[x**2 for x in range (1,4) if x%2==0]

[4]

In [36]:
[(x,y) for x in range(1,3) for y in range(4,6)]

[(1, 4), (1, 5), (2, 4), (2, 5)]

In [38]:
#Lambda functions
square=lambda x:x**2
square(3)

9

In [41]:
#map
my_list=[1,2,3,4,5]
list(map(lambda x:x*2, my_list))

[2, 4, 6, 8, 10]

In [42]:
#reduce

from functools import reduce
my_list=[1,2,3,4,5]
reduce(lambda x,y: x+y, my_list)

15

In [43]:
#filter

my_list=[1,2,3,4,5]
list(filter(lambda x:x%2==0, my_list))

[2, 4]

In [46]:
#sorted
my_list=[5,2,4,1,3]
sorted(my_list, key=lambda x:x%2==0)

[5, 1, 3, 2, 4]

# Numpy operation

np.min(array), mnp.max(array)   
array.sort()   
np.sort(array)   
np.partition(arry,2)  
np.concatenate((array1, array2)), np.vstack((array1, array2)) , np.hstack((array1, array2))

In [29]:
import numpy as np

#slicing
my_arry=np.array(my_list)
print(my_arry)
my_arry[1,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

In [7]:
#min, max
my_arry=np.array([my_list])
np.min(my_arry), np.max(my_arry)

(1, 8)

In [32]:
#Sort 
my_array = np.array([4, 2, 7, 1, 5])
my_array.sort()

In [33]:
np.sort(my_array)

array([1, 2, 4, 5, 7])

## Dictionary/Hash table vs. List/ArrayList: Very important!!

### Hashtable
key-value, not sorted.
Hash function to map key to index. O(1) time complexity, Fast access to elements based on keys. 


### ArrayList/Dynamic resizable list
ordered collection

In [ ]:
#######################
# When to use Hashtable
#######################
#Key-value mapping
user_info = {"user1": {"name": "Alice", "age": 25}, "user2": {"name": "Bob", "age": 30}}

#Fast lookup
dictionary = {"apple": "a fruit", "banana": "a fruit", "carrot": "a vegetable"}
if "banana" in dictionary:
    print(dictionary["banana"])  # Output: a fruit

##################
# When to use List
##################
#Ordered collection
task_list = ["Task 1", "Task 2", "Task 3"]

#Indexed access
fruits = ["apple", "banana", "orange"]
print(fruits[1])  # Output: banana

#Dynamic resizing
numbers = []
numbers.append(1)
numbers.append(2)
numbers.append(3)

In [48]:
#Dictionary

#Insertion
my_dict = {}  # An empty dictionary
my_dict["key1"] = "value1"  # Insert using assignment operator
my_dict.update({"key2": "value2"})  # Insert using update method
print(my_dict)  # Output: {'key1': 'value1', 'key2': 'value2'}

#Retrieval
my_dict = {"key1": "value1", "key2": "value2"}
value1 = my_dict["key1"]  # Retrieve using square bracket notation
value2 = my_dict.get("key2")  # Retrieve using get() method
print(value1)  # Output: 'value1'
print(value2)  # Output: 'value2'


#Deletion
my_dict = {"key1": "value1", "key2": "value2"}
del my_dict["key1"]  # Delete using del keyword
value = my_dict.pop("key2")  # Delete using pop() method
print(my_dict)  # Output: {}
print(value)  # Output: 'value2'

{'key1': 'value1', 'key2': 'value2'}
value1
value2
{}
value2


# Practice

#
Slicing, Reduce, Filter

### Reverse to make equal
Given two arrays A and B of length N, determine if there is a way to make A equal to B by reversing any subarrays from array B any number of times.  
Signature  
bool areTheyEqual(int[] arr_a, int[] arr_b)  
Input  
All integers in array are in the range [0, 1,000,000,000].  
Output  
Return true if B can be made equal to A, return false otherwise.  
Example  
A = [1, 2, 3, 4]   
B = [1, 4, 3, 2]  
output = true  
After reversing the subarray of B from indices 1 to 3, array B will equal array A.  


In [ ]:

import math

def are_they_equal(array_a, array_b):
  # Write your code here
  for i in range(len(arry_b)):
    if arry_b == reverseArray(arry_b[i::]):
      return True

def reverseArray(arry):
  left, right=0, len(arry)-1
  while left < right:
    arry[left], arry[right]=arry[right], arry[left]
    left, right=left +1, right-1
  


### 2. Passing Yearbooks
There are n students, numbered from 1 to n, each with their own yearbook. They would like to pass their yearbooks around and get them signed by other students.
You're given a list of n integers arr[1..n], which is guaranteed to be a permutation of 1..n (in other words, it includes the integers from 1 to n exactly once each, in some order). The meaning of this list is described below.
Initially, each student is holding their own yearbook. The students will then repeat the following two steps each minute: Each student i will first sign the yearbook that they're currently holding (which may either belong to themselves or to another student), and then they'll pass it to student arr[i-1]. It's possible that arr[i-1] = i for any given i, in which case student i will pass their yearbook back to themselves. Once a student has received their own yearbook back, they will hold on to it and no longer participate in the passing process.
It's guaranteed that, for any possible valid input, each student will eventually receive their own yearbook back and will never end up holding more than one yearbook at a time.
You must compute a list of n integers output, whose element at i-1 is equal to the number of signatures that will be present in student i's yearbook once they receive it back.
Signature
int[] findSignatureCounts(int[] arr)
Input
n is in the range [1, 100,000].
Each value arr[i] is in the range [1, n], and all values in arr[i] are distinct.
Output
Return a list of n integers output, as described above.
Example 1
n = 2
arr = [2, 1]
output = [2, 2]
Pass 1:
Student 1 signs their own yearbook. Then they pass the book to the student at arr[0], which is Student 2.
Student 2 signs their own yearbook. Then they pass the book to the student at arr[1], which is Student 1.
Pass 2:
Student 1 signs Student 2's yearbook. Then they pass it to the student at arr[0], which is Student 2.
Student 2 signs Student 1's yearbook. Then they pass it to the student at arr[1], which is Student 1.
Pass 3:
Both students now hold their own yearbook, so the process is complete.
Each student received 2 signatures.
Example 2
n = 2
arr = [1, 2]
output = [1, 1]
Pass 1:
Student 1 signs their own yearbook. Then they pass the book to the student at arr[0], which is themself, Student 1.
Student 2 signs their own yearbook. Then they pass the book to the student at arr[1], which is themself, Student 2.
Pass 2:
Both students now hold their own yearbook, so the process is complete.
Each student received 1 signature.

In [ ]:
import math
# Add any extra import statements you may need here


# Add any helper functions you may need here


def findSignatureCounts(arr):
  # Write your code here
  
  









# These are the tests we use to determine if the solution is correct.
# You can add your own at the bottom.

def printInteger(n):
  print('[', n, ']', sep='', end='')

def printIntegerList(array):
  size = len(array)
  print('[', end='')
  for i in range(size):
    if i != 0:
      print(', ', end='')
    print(array[i], end='')
  print(']', end='')

test_case_number = 1

def check(expected, output):
  global test_case_number
  expected_size = len(expected)
  output_size = len(output)
  result = True
  if expected_size != output_size:
    result = False
  for i in range(min(expected_size, output_size)):
    result &= (output[i] == expected[i])
  rightTick = '\u2713'
  wrongTick = '\u2717'
  if result:
    print(rightTick, 'Test #', test_case_number, sep='')
  else:
    print(wrongTick, 'Test #', test_case_number, ': Expected ', sep='', end='')
    printIntegerList(expected)
    print(' Your output: ', end='')
    printIntegerList(output)
    print()
  test_case_number += 1

if __name__ == "__main__":
  arr_1 = [2, 1]
  expected_1 = [2, 2]
  output_1 = findSignatureCounts(arr_1)
  check(expected_1, output_1)

  arr_2 = [1, 2]
  expected_2 = [1, 1]
  output_2 = findSignatureCounts(arr_2)
  check(expected_2, output_2)


  # Add your own test cases here
  

## 3. Contiguous Subarrays
You are given an array arr of N integers. For each index i, you are required to determine the number of contiguous subarrays that fulfill the following conditions:
The value at index i must be the maximum element in the contiguous subarrays, and
These contiguous subarrays must either start from or end on index i.
Signature
int[] countSubarrays(int[] arr)
Input
Array arr is a non-empty list of unique integers that range between 1 to 1,000,000,000
Size N is between 1 and 1,000,000
Output
An array where each index i contains an integer denoting the maximum number of contiguous subarrays of arr[i]
Example:
arr = [3, 4, 1, 6, 2]
output = [1, 3, 1, 5, 1]
Explanation:
For index 0 - [3] is the only contiguous subarray that starts (or ends) at index 0 with the maximum value in the subarray being 3.
For index 1 - [4], [3, 4], [4, 1]
For index 2 - [1]
For index 3 - [6], [6, 2], [1, 6], [4, 1, 6], [3, 4, 1, 6]
For index 4 - [2]
So, the answer for the above input is [1, 3, 1, 5, 1]

In [ ]:
import math
# Add any extra import statements you may need here


# Add any helper functions you may need here


def count_subarrays(arr):
  # Write your code here
  
   




# These are the tests we use to determine if the solution is correct.
# You can add your own at the bottom.

def printInteger(n):
  print('[', n, ']', sep='', end='')

def printIntegerList(array):
  size = len(array)
  print('[', end='')
  for i in range(size):
    if i != 0:
      print(', ', end='')
    print(array[i], end='')
  print(']', end='')

test_case_number = 1

def check(expected, output):
  global test_case_number
  expected_size = len(expected)
  output_size = len(output)
  result = True
  if expected_size != output_size:
    result = False
  for i in range(min(expected_size, output_size)):
    result &= (output[i] == expected[i])
  rightTick = '\u2713'
  wrongTick = '\u2717'
  if result:
    print(rightTick, 'Test #', test_case_number, sep='')
  else:
    print(wrongTick, 'Test #', test_case_number, ': Expected ', sep='', end='')
    printIntegerList(expected)
    print(' Your output: ', end='')
    printIntegerList(output)
    print()
  test_case_number += 1

if __name__ == "__main__":
  test_1 = [3, 4, 1, 6, 2]
  expected_1 = [1, 3, 1, 5, 1]
  output_1 = count_subarrays(test_1)
  check(expected_1, output_1)
  
  test_2 = [2, 4, 7, 1, 5, 3]
  expected_2 = [1, 2, 6, 1, 3, 1]
  output_2 = count_subarrays(test_2)
  check(expected_2, output_2)

  # Add your own test cases here
  

# Leet code

## Two pointers

In [1]:
#Example 1: Given a string s, return true if it is a palindrome, false otherwise.
#A string is a palindrome if it reads the same forward as backward. That means, 
#after reversing it, it is still the same string. For example: "abcdcba", or "racecar".

def isPalindrome(s:str)-> bool:
    left=0
    right=len(s)-1
    while left < right:
        if s[left] != s[right]:
            return False
        left, right=left+1, right-1
    return True

isPalindrome("racecar")

True

In [1]:
#Example 2: Given a sorted array of unique integers and a target integer, 
#return true if there exists a pair of numbers that sum to target, false otherwise. 
#This problem is similar to Two Sum. For example, given 
#nums = [1, 2, 4, 6, 8, 9, 14, 15] and target = 13, return true because 4 + 9 = 13.

def isSumToTarget(nums:list[int], target:int)->bool:
    left =0
    right=len(nums)-1

    while left < right:
        currentSum=nums[left]+nums[right]
        if currentSum == target:
            return True
        elif currentSum > target:
            right -=1
        else:
            left +=1
    
    return False

nums=[1, 2, 4, 6, 8, 9, 14, 15]
target=13
isSumToTarget(nums, target)


True

In [2]:
#Example 3: Given two sorted integer arrays arr1 and arr2, 
#return a new array that combines both of them and is also sorted.

arr_1= [1,4,7,20]
arr_2=[3,5,6]
ans_lst=[]

def combine_twoarrays(arr_1:list[int], arr_2:list[int])-> list[int]:
    i,j=0,0
    while i < len(arr_1) and j < len(arr_2):
        if arr_1[i] < arr_2[j]:
            ans_lst.append(arr_1[i])
            i +=1
        else:
            ans_lst.append(arr_2[j])
            j +=1

    while i < len(arr_1):
        ans_lst.append(arr_1[i])
        i +=1

    while j < len(arr_2):
        ans_lst.append(arr_2[j])
        j +=1

    return ans_lst

combine_twoarrays(arr_1, arr_2)

[1, 3, 4, 5, 6, 7, 20]

In [3]:
# Given two strings s and t, return true if s is a subsequence of t, or false otherwise.
# A subsequence of a string is a sequence of characters that can be obtained by 
# deleting some (or none) of the characters from the original string, while maintaining
# the relative order of the remaining characters. 
# For example, "ace" is a subsequence of "abcde" while "aec" is not.

def isSubsequence (s:str, t:str)->bool:
    i,j=0,0
    while i <len(s) and j<len(t):
        if s[i]==t[j]:
            i +=1
        j +=1
    return i==len(s)

s="abc"
t="ahbgdc"
isSubsequence(s,t)

True

In [14]:
# reverse String
#Write a function that reverses a string. The input string is given as an array of 
#characters s.You must do this by modifying the input array in-place with O(1) extra memory.

def reverseString(s:list[str], left:int, right:int)->None:
    while left < right:
        s[left], s[right]=s[right], s[left]
        left, right=left+1, right-1
    return 

def reverseString_recursively(s:list[str], left:int, right:int)->list[str]:
    if left < right:
        s[left], s[right]=s[right], s[left]
        left, right=left+1, right-1
        reverseString_recursively(s, left, right)
    return 
    

s = ["h","e","l","l","o"]
reverseString(s, left=0, right=len(s)-1)
print(s)
reverseString_recursively(s, 0, len(s)-1)
print(s)

['o', 'l', 'l', 'e', 'h']
['h', 'e', 'l', 'l', 'o']


In [11]:
#Given an integer array nums sorted in non-decreasing order, 
#return an array of the squares of each number sorted in non-decreasing order.

nums = [-4,-1,0,3,10]

def square1(nums):
    sortedlist=[]
    for i in range(len(nums)):
        sortedlist.append(nums[i]**2) #squre is O(n)
    return sorted(sortedlist) #sorting is Timsort, O(n)

#Time Complexity: O(Nlog⁡N), Space complexity : O(N) or O(log⁡N) 
def square2(nums:list[int])-> list[int]:
    squarelst=[x**2 for x in nums]
    return sorted(squarelst) # Timsort O(N)

#two pointers; time complexity O(n)
def square3(nums):

    left=0
    right=len(nums)-1
    result=[0]*len(nums)

    for i in range(len(nums)-1, -1, -1):
        if abs(nums[left]) < abs(nums[right]):
            square=nums[right]
            right-=1
        else: 
            square=nums[left]
            left+=1
        
        result[i]=square**2
    return result 

 
    
%timeit square1(nums) # 3.07 µs
%timeit square2(nums) # 2.47 µs
%timeit square3(nums) # 3.61 µs

2.87 µs ± 39.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.47 µs ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
3.61 µs ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Sliding window

Find Valid subarray

* Find the longest subarray with a sum less than or equal to k  
* Find the longest substring that has at most one "0"  
* Find the number of subarrays that have a product less than k  


In [1]:
#Example 1: Given an array of positive integers nums and an integer k, 
#find the length of the longest subarray whose sum is less than or equal to k.

def maxSubArrayLen(nums:list[int], k:int)->int:
    max_len=0
    for i in range(len(nums)):
        for j in range(i+1, len(nums)+1):
            if sum(nums[i:j]) <= k:
                max_len=max(max_len, j-i)
    return max_len
 
nums=[1, -1, 5, -2, 3]
k=3
maxSubArrayLen(nums, k)

4

In [14]:
def find_maxlength(nums:list[int], k:int)->list[int, list[int]]:
    left=currSum= maxLength=0
    for right in range(len(nums)):
        currSum +=nums[right]
        while currSum > k:
            left +=1
            currSum -= nums[left]

        maxLength=max(maxLength, right-left+1) 
        substr=nums[left:right+1]

    return maxLength, substr

k=8
nums=[3,1,2,7,4,2,1,1,5]

find_maxlength(nums, k)

(4, [1, 5])

In [17]:
# Example 2: You are given a binary string s (a string containing only "0" and "1"). 
# You may choose up to one "0" and flip it to a "1". What is the length of the longest substring 
# achievable that contains only "1"?
# For example, given s = "1101100111", the answer is 5. If you perform the flip at index 2, 
#the string becomes 1111100111.

def find_lengthOfOne(s:list[int])->int:
    left=currentCount=maxCount=0

    for right in range(len(s)):
        if s[right]=='0': #flip
            currentCount+=1
        while currentCount >1:
            if s[left] =='0':
                currentCount-=1
            left +=1
        maxCount=max(maxCount, right-left+1)
    return maxCount

s="1101100111"
find_lengthOfOne(s)



5

## Prefix sum

In [ ]:
#Example 1: Given an integer array nums, an array queries where queries[i] = [x, y] and 
#an integer limit, return a boolean array that represents the answer to each query.
# A query is true if the sum of the subarray from x to y is less than limit, or false otherwise.
#For example, given nums = [1, 6, 3, 2, 7, 2], queries = [[0, 3], [2, 5], [2, 4]], 
#and limit = 13, the answer is [true, false, true]. For each query, the subarray sums are 
#[12, 14, 12].



In [ ]:
#Example 2: 2270. Number of Ways to Split Array
#Given an integer array nums, find the number of ways to split the array into two parts 
#so that the first section has a sum greater than or equal to the sum of the second section.
#The second section should have at least one number.



In [ ]:
# 